### ISSUE TITLE
assert not raiseOnReferenceGaps raised on sequences that shouldn't.

### ISSUE THREAD

**Issue by bamueh** [VirologyCharite/gb2seq#1]
On some sequences the following error occurs, even though it shouldn't:

```
$ python ~/dark-matter/2019-nCoV-sequences/bin/get-spikes.py < error.in
Traceback (most recent call last):
  File "/Users/barbara/dark-matter/2019-nCoV-sequences/bin/get-spikes.py", line 68, in <module>
    main(args)
  File "/Users/barbara/dark-matter/2019-nCoV-sequences/bin/get-spikes.py", line 32, in main
    referenceAa, genomeAa = alignment.aaSequences('spike')
  File "/Users/barbara/dark-matter/gb2seq/gb2seq/alignment.py", line 411, in aaSequences
    assert not raiseOnReferenceGaps
AssertionError
```

**Comment by bamueh** [comment]
Duh, found the `raiseOnReferenceGaps=False` argument to `Gb2Alignment.aaSequences`. Closing this and fixing it in the sequences repo.
