### ISSUE TITLE
local variable 'forward' referenced before assignment

### ISSUE THREAD

**Issue by terrycojones** [VirologyCharite/gb2seq#11]
Using the `NC_001896.1.` GenBank file (fetched with the dark-matter script, but you can just download it yourself it you don't have that) `ncbi-fetch-id.py --format gb NC_001896.1 > NC_001896.1.gb`, I get this:

```sh
$ describe-feature.py --reference NC_001896.1.gb
Traceback (most recent call last):
  File "/Users/terry/charite/gb2seq/bin/describe-feature.py", line 251, in <module>
    main(args)
  File "/Users/terry/charite/gb2seq/bin/describe-feature.py", line 123, in main
    features = Features(
  File "/Users/terry/charite/gb2seq/gb2seq/features.py", line 136, in __init__
    self._initializeFromGenBankRecord(record, alsoInclude)
  File "/Users/terry/charite/gb2seq/gb2seq/features.py", line 287, in _initializeFromGenBankRecord
    "forward": forward,
UnboundLocalError: local variable 'forward' referenced before assignment
```

**Comment by terrycojones** [comment]
This occurs because HBV has multiple genome ranges specified for some genes (it is circular, so the gene offsets cross zero).
