### ISSUE TITLE
KeyError: 'rpt_type'

### ISSUE THREAD

**Issue by Mailinnia** [VirologyCharite/gb2seq#3]
I'm trying to use your tool to annotate another sequence (both can be found on NCBI):
```
annotate-genome.py --reference FR682468.2.gb --genome MH681419.1.fasta --aligner mafft
```

However, I keep getting following error:

```
Traceback (most recent call last):
  File "/gb2seq_env/bin/annotate-genome.py", line 73, in <module>
    sys.exit(main(makeParser().parse_args()))
  File "/gb2seq_env/bin/annotate-genome.py", line 21, in main
    features = Features(args.reference, sars2=args.sars2)
  File "/gb2seq_env/lib/python3.9/site-packages/gb2seq/features.py", line 129, in __init__
    self._initializeFromGenBankRecord(record)
  File "/gb2seq_env/lib/python3.9/site-packages/gb2seq/features.py", line 227, in _initializeFromGenBankRecord
    value["type"] = feature.qualifiers["rpt_type"][0]
KeyError: 'rpt_type'
```

**Comment by Mailinnia** [comment]
I am running into more than one issue.
The annotated FR682468.2 has no "product" or "rpt_type" in feature.qualifiers, so it fails in the features.py script.
I've solved this with some if statements.

```
...
elif type_ == "repeat_region":
	for n in itertools.count(1):
		name = f"repeat region {n}"
		if name not in self:
			break
	if 'rpt_type' in feature.qualifiers:
		value["type"] = feature.qualifiers["rpt_type"][0]
	else:
		value["type"] = 'unknown'

elif type_ in {"CDS", "mat_peptide"}:
	if 'product' in feature.qualifiers:
		name = feature.qualifiers["product"][0]
	else:
		name = feature.qualifiers["protein_id"][0]
	value["product"] = name
...
```

Then I ran into an issue with it reporting the wrong orf for a CDS which is in the reference but not in the target genome. I don't know why this would happen, but I solved that by counting the number of gaps vs len of alignment in the annotate.py:

```
for feature in sorted(features.values(), key=itemgetter("start")):
	name = feature["name"]
	forward = feature["forward"]
	# print(name)
	referenceAA, genomeAA = alignment.aaSequences(name, raiseOnReferenceGaps=False)

	gappedOffset = alignment.gappedOffsets[feature["start"]]
	genomeStart = (
	gappedOffset - alignment.genomeAligned.sequence[:gappedOffset].count("-"))
	
	######## solution down here ###############
	aend = alignmentEnd(
		alignment.referenceAligned.sequence,
		gappedOffset,
		feature["stop"] - feature["start"],
	)
	genome_align = alignment.genomeAligned.sequence[gappedOffset:aend]
	genome_gap_count = len(genome_align)-genome_align.count('-')
	genome_N_count = len(genome_align)-genome_align.count('N')
	if not genome_gap_count > 0:
		continue
        if not genome_N_count > 0:
            continue
			 
		
	################## 
```

Then I also ran into an issue with failing the assert statements ```assert 0 <= gappedOffset < len(genome)``` in annotate.py.
However, the reported positions genomeStart and genomeStop seemed correct.
So I commented out the two assert statements:

```
... 
#assert 0 <= gappedOffset < len(genome)
...
...
#assert 0 <= reverseStart < len(genome)
...
```
and replaced them:

```
...
# Small sanity check.
        if not orf["foundStartCodon"]:
            assert genomeAA.sequence[0] != "M"
        # print('blob6')
        genomeStart = gappedOffset - alignment.genomeAligned.sequence[
            :gappedOffset
        ].count("-")
        genomeStop = genomeStart + orf["length"] * 3
               
        ##############replace assert #############################
        assert 0 <= genomeStop < len(genome)
        ###########################################
        resultFeatures[name] = {
            "genome": {
                "start": genomeStart,
                "stop": genomeStop,
                "sequence": orf["sequence"],
                "translation": orf["translation"],
            },
            "reference": feature,
        }

... 
```

and now things seem to work pretty well.

**Comment by Mailinnia** [comment]
I ran into another issue, where the gene positions were reported wrong for reverse/complement genes, if they had an early stop codon, or no stop codon in the target genome.

I solved that by adding the following to the annotate.py:
```
        # Small sanity check.
        if not orf["foundStartCodon"]:
            assert genomeAA.sequence[0] != "M"
        ############## Solution here ######################
        if forward:
            genomeStart = gappedOffset - alignment.genomeAligned.sequence[:gappedOffset].count("-")
            genomeStop = genomeStart + orf["length"] * 3
        else:
            genomeStop = reverseGappedOffset - alignment.genomeAligned.sequence[:aend].count("-")
            genomeStart = genomeStop - orf["length"] * 3
         #######################################################
 ```

**Comment by terrycojones** [comment]
Hi @Mailinnia I'm sorry, I only just saw all these comments! We will look at this carefully and get you an answer. Sorry for the long delay, I don't know how I missed this.
